//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administracion.WSTramitesOnline {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Administracion.WSTramitesOnline.Empleado))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Administracion.WSTramitesOnline.Solicitante))]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompletoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCompleto {
            get {
                return this.NombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompletoField, value) != true)) {
                    this.NombreCompletoField = value;
                    this.RaisePropertyChanged("NombreCompleto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class Empleado : Administracion.WSTramitesOnline.Usuario {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraEntradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraSalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Administracion.WSTramitesOnline.HoraExtra[] HorasExtrasGeneradasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraEntrada {
            get {
                return this.HoraEntradaField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraEntradaField, value) != true)) {
                    this.HoraEntradaField = value;
                    this.RaisePropertyChanged("HoraEntrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraSalida {
            get {
                return this.HoraSalidaField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraSalidaField, value) != true)) {
                    this.HoraSalidaField = value;
                    this.RaisePropertyChanged("HoraSalida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Administracion.WSTramitesOnline.HoraExtra[] HorasExtrasGeneradas {
            get {
                return this.HorasExtrasGeneradasField;
            }
            set {
                if ((object.ReferenceEquals(this.HorasExtrasGeneradasField, value) != true)) {
                    this.HorasExtrasGeneradasField = value;
                    this.RaisePropertyChanged("HorasExtrasGeneradas");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Solicitante", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class Solicitante : Administracion.WSTramitesOnline.Usuario {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HoraExtra", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class HoraExtra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinutosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Minutos {
            get {
                return this.MinutosField;
            }
            set {
                if ((this.MinutosField.Equals(value) != true)) {
                    this.MinutosField = value;
                    this.RaisePropertyChanged("Minutos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Documento", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class Documento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LugarSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LugarSolicitud {
            get {
                return this.LugarSolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.LugarSolicitudField, value) != true)) {
                    this.LugarSolicitudField = value;
                    this.RaisePropertyChanged("LugarSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Solicitud", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class Solicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Administracion.WSTramitesOnline.Solicitante EmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Administracion.WSTramitesOnline.TipoTramite TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Administracion.WSTramitesOnline.Solicitante Emisor {
            get {
                return this.EmisorField;
            }
            set {
                if ((object.ReferenceEquals(this.EmisorField, value) != true)) {
                    this.EmisorField = value;
                    this.RaisePropertyChanged("Emisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaHora {
            get {
                return this.FechaHoraField;
            }
            set {
                if ((this.FechaHoraField.Equals(value) != true)) {
                    this.FechaHoraField = value;
                    this.RaisePropertyChanged("FechaHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Administracion.WSTramitesOnline.TipoTramite Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoTramite", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class TipoTramite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Administracion.WSTramitesOnline.Documento[] DocumentosRequeridosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Administracion.WSTramitesOnline.Documento[] DocumentosRequeridos {
            get {
                return this.DocumentosRequeridosField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentosRequeridosField, value) != true)) {
                    this.DocumentosRequeridosField = value;
                    this.RaisePropertyChanged("DocumentosRequeridos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSTramitesOnline.IServicioTramitesOnline")]
    public interface IServicioTramitesOnline {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/Registro", ReplyAction="http://tempuri.org/IServicioTramitesOnline/RegistroResponse")]
        void Registro(Administracion.WSTramitesOnline.Usuario usuario, Administracion.WSTramitesOnline.Empleado empleadoLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/Registro", ReplyAction="http://tempuri.org/IServicioTramitesOnline/RegistroResponse")]
        System.Threading.Tasks.Task RegistroAsync(Administracion.WSTramitesOnline.Usuario usuario, Administracion.WSTramitesOnline.Empleado empleadoLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/Login", ReplyAction="http://tempuri.org/IServicioTramitesOnline/LoginResponse")]
        Administracion.WSTramitesOnline.Usuario Login(string usuarioLogin, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/Login", ReplyAction="http://tempuri.org/IServicioTramitesOnline/LoginResponse")]
        System.Threading.Tasks.Task<Administracion.WSTramitesOnline.Usuario> LoginAsync(string usuarioLogin, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/AgregarDocumento", ReplyAction="http://tempuri.org/IServicioTramitesOnline/AgregarDocumentoResponse")]
        void AgregarDocumento(Administracion.WSTramitesOnline.Documento nuevoDoc, Administracion.WSTramitesOnline.Empleado userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/AgregarDocumento", ReplyAction="http://tempuri.org/IServicioTramitesOnline/AgregarDocumentoResponse")]
        System.Threading.Tasks.Task AgregarDocumentoAsync(Administracion.WSTramitesOnline.Documento nuevoDoc, Administracion.WSTramitesOnline.Empleado userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/ModificarDocumento", ReplyAction="http://tempuri.org/IServicioTramitesOnline/ModificarDocumentoResponse")]
        void ModificarDocumento(Administracion.WSTramitesOnline.Documento doc, Administracion.WSTramitesOnline.Empleado userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/ModificarDocumento", ReplyAction="http://tempuri.org/IServicioTramitesOnline/ModificarDocumentoResponse")]
        System.Threading.Tasks.Task ModificarDocumentoAsync(Administracion.WSTramitesOnline.Documento doc, Administracion.WSTramitesOnline.Empleado userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/EliminarDocumento", ReplyAction="http://tempuri.org/IServicioTramitesOnline/EliminarDocumentoResponse")]
        void EliminarDocumento(int id, Administracion.WSTramitesOnline.Empleado userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/EliminarDocumento", ReplyAction="http://tempuri.org/IServicioTramitesOnline/EliminarDocumentoResponse")]
        System.Threading.Tasks.Task EliminarDocumentoAsync(int id, Administracion.WSTramitesOnline.Empleado userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/BuscarDocumento", ReplyAction="http://tempuri.org/IServicioTramitesOnline/BuscarDocumentoResponse")]
        Administracion.WSTramitesOnline.Documento BuscarDocumento(int id, Administracion.WSTramitesOnline.Usuario userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/BuscarDocumento", ReplyAction="http://tempuri.org/IServicioTramitesOnline/BuscarDocumentoResponse")]
        System.Threading.Tasks.Task<Administracion.WSTramitesOnline.Documento> BuscarDocumentoAsync(int id, Administracion.WSTramitesOnline.Usuario userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/ObtenerDocumentos", ReplyAction="http://tempuri.org/IServicioTramitesOnline/ObtenerDocumentosResponse")]
        Administracion.WSTramitesOnline.Documento[] ObtenerDocumentos(Administracion.WSTramitesOnline.Empleado userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/ObtenerDocumentos", ReplyAction="http://tempuri.org/IServicioTramitesOnline/ObtenerDocumentosResponse")]
        System.Threading.Tasks.Task<Administracion.WSTramitesOnline.Documento[]> ObtenerDocumentosAsync(Administracion.WSTramitesOnline.Empleado userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/AgregarEmpleado", ReplyAction="http://tempuri.org/IServicioTramitesOnline/AgregarEmpleadoResponse")]
        void AgregarEmpleado(Administracion.WSTramitesOnline.Empleado empleado, Administracion.WSTramitesOnline.Empleado userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/AgregarEmpleado", ReplyAction="http://tempuri.org/IServicioTramitesOnline/AgregarEmpleadoResponse")]
        System.Threading.Tasks.Task AgregarEmpleadoAsync(Administracion.WSTramitesOnline.Empleado empleado, Administracion.WSTramitesOnline.Empleado userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/ModificarEmpleado", ReplyAction="http://tempuri.org/IServicioTramitesOnline/ModificarEmpleadoResponse")]
        void ModificarEmpleado(Administracion.WSTramitesOnline.Empleado empleado, Administracion.WSTramitesOnline.Empleado userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/ModificarEmpleado", ReplyAction="http://tempuri.org/IServicioTramitesOnline/ModificarEmpleadoResponse")]
        System.Threading.Tasks.Task ModificarEmpleadoAsync(Administracion.WSTramitesOnline.Empleado empleado, Administracion.WSTramitesOnline.Empleado userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/EliminarEmpleado", ReplyAction="http://tempuri.org/IServicioTramitesOnline/EliminarEmpleadoResponse")]
        void EliminarEmpleado(Administracion.WSTramitesOnline.Empleado empleado, Administracion.WSTramitesOnline.Empleado userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/EliminarEmpleado", ReplyAction="http://tempuri.org/IServicioTramitesOnline/EliminarEmpleadoResponse")]
        System.Threading.Tasks.Task EliminarEmpleadoAsync(Administracion.WSTramitesOnline.Empleado empleado, Administracion.WSTramitesOnline.Empleado userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/BuscarEmpleado", ReplyAction="http://tempuri.org/IServicioTramitesOnline/BuscarEmpleadoResponse")]
        Administracion.WSTramitesOnline.Empleado BuscarEmpleado(string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/BuscarEmpleado", ReplyAction="http://tempuri.org/IServicioTramitesOnline/BuscarEmpleadoResponse")]
        System.Threading.Tasks.Task<Administracion.WSTramitesOnline.Empleado> BuscarEmpleadoAsync(string documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/AgregarHoraExtra", ReplyAction="http://tempuri.org/IServicioTramitesOnline/AgregarHoraExtraResponse")]
        void AgregarHoraExtra(Administracion.WSTramitesOnline.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/AgregarHoraExtra", ReplyAction="http://tempuri.org/IServicioTramitesOnline/AgregarHoraExtraResponse")]
        System.Threading.Tasks.Task AgregarHoraExtraAsync(Administracion.WSTramitesOnline.Empleado empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/AgregarSolicitud", ReplyAction="http://tempuri.org/IServicioTramitesOnline/AgregarSolicitudResponse")]
        void AgregarSolicitud(Administracion.WSTramitesOnline.Solicitud solicitud, Administracion.WSTramitesOnline.Solicitante userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/AgregarSolicitud", ReplyAction="http://tempuri.org/IServicioTramitesOnline/AgregarSolicitudResponse")]
        System.Threading.Tasks.Task AgregarSolicitudAsync(Administracion.WSTramitesOnline.Solicitud solicitud, Administracion.WSTramitesOnline.Solicitante userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/CambiarEstado", ReplyAction="http://tempuri.org/IServicioTramitesOnline/CambiarEstadoResponse")]
        void CambiarEstado(Administracion.WSTramitesOnline.Solicitud solicitud, Administracion.WSTramitesOnline.Empleado userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/CambiarEstado", ReplyAction="http://tempuri.org/IServicioTramitesOnline/CambiarEstadoResponse")]
        System.Threading.Tasks.Task CambiarEstadoAsync(Administracion.WSTramitesOnline.Solicitud solicitud, Administracion.WSTramitesOnline.Empleado userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/ListadoSolicitudes", ReplyAction="http://tempuri.org/IServicioTramitesOnline/ListadoSolicitudesResponse")]
        Administracion.WSTramitesOnline.Solicitud[] ListadoSolicitudes(Administracion.WSTramitesOnline.Empleado userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/ListadoSolicitudes", ReplyAction="http://tempuri.org/IServicioTramitesOnline/ListadoSolicitudesResponse")]
        System.Threading.Tasks.Task<Administracion.WSTramitesOnline.Solicitud[]> ListadoSolicitudesAsync(Administracion.WSTramitesOnline.Empleado userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/AgregarTramite", ReplyAction="http://tempuri.org/IServicioTramitesOnline/AgregarTramiteResponse")]
        void AgregarTramite(Administracion.WSTramitesOnline.TipoTramite tramite, Administracion.WSTramitesOnline.Empleado userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/AgregarTramite", ReplyAction="http://tempuri.org/IServicioTramitesOnline/AgregarTramiteResponse")]
        System.Threading.Tasks.Task AgregarTramiteAsync(Administracion.WSTramitesOnline.TipoTramite tramite, Administracion.WSTramitesOnline.Empleado userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/ModificarTramite", ReplyAction="http://tempuri.org/IServicioTramitesOnline/ModificarTramiteResponse")]
        void ModificarTramite(Administracion.WSTramitesOnline.TipoTramite tramite, Administracion.WSTramitesOnline.Empleado user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/ModificarTramite", ReplyAction="http://tempuri.org/IServicioTramitesOnline/ModificarTramiteResponse")]
        System.Threading.Tasks.Task ModificarTramiteAsync(Administracion.WSTramitesOnline.TipoTramite tramite, Administracion.WSTramitesOnline.Empleado user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/EliminarTramite", ReplyAction="http://tempuri.org/IServicioTramitesOnline/EliminarTramiteResponse")]
        void EliminarTramite(Administracion.WSTramitesOnline.TipoTramite tramite, Administracion.WSTramitesOnline.Empleado user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/EliminarTramite", ReplyAction="http://tempuri.org/IServicioTramitesOnline/EliminarTramiteResponse")]
        System.Threading.Tasks.Task EliminarTramiteAsync(Administracion.WSTramitesOnline.TipoTramite tramite, Administracion.WSTramitesOnline.Empleado user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/ObtenerTramites", ReplyAction="http://tempuri.org/IServicioTramitesOnline/ObtenerTramitesResponse")]
        Administracion.WSTramitesOnline.TipoTramite[] ObtenerTramites();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/ObtenerTramites", ReplyAction="http://tempuri.org/IServicioTramitesOnline/ObtenerTramitesResponse")]
        System.Threading.Tasks.Task<Administracion.WSTramitesOnline.TipoTramite[]> ObtenerTramitesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/ObtenerTipoTramites", ReplyAction="http://tempuri.org/IServicioTramitesOnline/ObtenerTipoTramitesResponse")]
        string ObtenerTipoTramites();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/ObtenerTipoTramites", ReplyAction="http://tempuri.org/IServicioTramitesOnline/ObtenerTipoTramitesResponse")]
        System.Threading.Tasks.Task<string> ObtenerTipoTramitesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/BuscarTramite", ReplyAction="http://tempuri.org/IServicioTramitesOnline/BuscarTramiteResponse")]
        Administracion.WSTramitesOnline.TipoTramite BuscarTramite(string idTramite, Administracion.WSTramitesOnline.Empleado user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioTramitesOnline/BuscarTramite", ReplyAction="http://tempuri.org/IServicioTramitesOnline/BuscarTramiteResponse")]
        System.Threading.Tasks.Task<Administracion.WSTramitesOnline.TipoTramite> BuscarTramiteAsync(string idTramite, Administracion.WSTramitesOnline.Empleado user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioTramitesOnlineChannel : Administracion.WSTramitesOnline.IServicioTramitesOnline, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioTramitesOnlineClient : System.ServiceModel.ClientBase<Administracion.WSTramitesOnline.IServicioTramitesOnline>, Administracion.WSTramitesOnline.IServicioTramitesOnline {
        
        public ServicioTramitesOnlineClient() {
        }
        
        public ServicioTramitesOnlineClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioTramitesOnlineClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTramitesOnlineClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTramitesOnlineClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Registro(Administracion.WSTramitesOnline.Usuario usuario, Administracion.WSTramitesOnline.Empleado empleadoLogin) {
            base.Channel.Registro(usuario, empleadoLogin);
        }
        
        public System.Threading.Tasks.Task RegistroAsync(Administracion.WSTramitesOnline.Usuario usuario, Administracion.WSTramitesOnline.Empleado empleadoLogin) {
            return base.Channel.RegistroAsync(usuario, empleadoLogin);
        }
        
        public Administracion.WSTramitesOnline.Usuario Login(string usuarioLogin, string contrasena) {
            return base.Channel.Login(usuarioLogin, contrasena);
        }
        
        public System.Threading.Tasks.Task<Administracion.WSTramitesOnline.Usuario> LoginAsync(string usuarioLogin, string contrasena) {
            return base.Channel.LoginAsync(usuarioLogin, contrasena);
        }
        
        public void AgregarDocumento(Administracion.WSTramitesOnline.Documento nuevoDoc, Administracion.WSTramitesOnline.Empleado userLogin) {
            base.Channel.AgregarDocumento(nuevoDoc, userLogin);
        }
        
        public System.Threading.Tasks.Task AgregarDocumentoAsync(Administracion.WSTramitesOnline.Documento nuevoDoc, Administracion.WSTramitesOnline.Empleado userLogin) {
            return base.Channel.AgregarDocumentoAsync(nuevoDoc, userLogin);
        }
        
        public void ModificarDocumento(Administracion.WSTramitesOnline.Documento doc, Administracion.WSTramitesOnline.Empleado userLogin) {
            base.Channel.ModificarDocumento(doc, userLogin);
        }
        
        public System.Threading.Tasks.Task ModificarDocumentoAsync(Administracion.WSTramitesOnline.Documento doc, Administracion.WSTramitesOnline.Empleado userLogin) {
            return base.Channel.ModificarDocumentoAsync(doc, userLogin);
        }
        
        public void EliminarDocumento(int id, Administracion.WSTramitesOnline.Empleado userLogin) {
            base.Channel.EliminarDocumento(id, userLogin);
        }
        
        public System.Threading.Tasks.Task EliminarDocumentoAsync(int id, Administracion.WSTramitesOnline.Empleado userLogin) {
            return base.Channel.EliminarDocumentoAsync(id, userLogin);
        }
        
        public Administracion.WSTramitesOnline.Documento BuscarDocumento(int id, Administracion.WSTramitesOnline.Usuario userLogin) {
            return base.Channel.BuscarDocumento(id, userLogin);
        }
        
        public System.Threading.Tasks.Task<Administracion.WSTramitesOnline.Documento> BuscarDocumentoAsync(int id, Administracion.WSTramitesOnline.Usuario userLogin) {
            return base.Channel.BuscarDocumentoAsync(id, userLogin);
        }
        
        public Administracion.WSTramitesOnline.Documento[] ObtenerDocumentos(Administracion.WSTramitesOnline.Empleado userLogin) {
            return base.Channel.ObtenerDocumentos(userLogin);
        }
        
        public System.Threading.Tasks.Task<Administracion.WSTramitesOnline.Documento[]> ObtenerDocumentosAsync(Administracion.WSTramitesOnline.Empleado userLogin) {
            return base.Channel.ObtenerDocumentosAsync(userLogin);
        }
        
        public void AgregarEmpleado(Administracion.WSTramitesOnline.Empleado empleado, Administracion.WSTramitesOnline.Empleado userLogin) {
            base.Channel.AgregarEmpleado(empleado, userLogin);
        }
        
        public System.Threading.Tasks.Task AgregarEmpleadoAsync(Administracion.WSTramitesOnline.Empleado empleado, Administracion.WSTramitesOnline.Empleado userLogin) {
            return base.Channel.AgregarEmpleadoAsync(empleado, userLogin);
        }
        
        public void ModificarEmpleado(Administracion.WSTramitesOnline.Empleado empleado, Administracion.WSTramitesOnline.Empleado userLogin) {
            base.Channel.ModificarEmpleado(empleado, userLogin);
        }
        
        public System.Threading.Tasks.Task ModificarEmpleadoAsync(Administracion.WSTramitesOnline.Empleado empleado, Administracion.WSTramitesOnline.Empleado userLogin) {
            return base.Channel.ModificarEmpleadoAsync(empleado, userLogin);
        }
        
        public void EliminarEmpleado(Administracion.WSTramitesOnline.Empleado empleado, Administracion.WSTramitesOnline.Empleado userLogin) {
            base.Channel.EliminarEmpleado(empleado, userLogin);
        }
        
        public System.Threading.Tasks.Task EliminarEmpleadoAsync(Administracion.WSTramitesOnline.Empleado empleado, Administracion.WSTramitesOnline.Empleado userLogin) {
            return base.Channel.EliminarEmpleadoAsync(empleado, userLogin);
        }
        
        public Administracion.WSTramitesOnline.Empleado BuscarEmpleado(string documento) {
            return base.Channel.BuscarEmpleado(documento);
        }
        
        public System.Threading.Tasks.Task<Administracion.WSTramitesOnline.Empleado> BuscarEmpleadoAsync(string documento) {
            return base.Channel.BuscarEmpleadoAsync(documento);
        }
        
        public void AgregarHoraExtra(Administracion.WSTramitesOnline.Empleado empleado) {
            base.Channel.AgregarHoraExtra(empleado);
        }
        
        public System.Threading.Tasks.Task AgregarHoraExtraAsync(Administracion.WSTramitesOnline.Empleado empleado) {
            return base.Channel.AgregarHoraExtraAsync(empleado);
        }
        
        public void AgregarSolicitud(Administracion.WSTramitesOnline.Solicitud solicitud, Administracion.WSTramitesOnline.Solicitante userLogin) {
            base.Channel.AgregarSolicitud(solicitud, userLogin);
        }
        
        public System.Threading.Tasks.Task AgregarSolicitudAsync(Administracion.WSTramitesOnline.Solicitud solicitud, Administracion.WSTramitesOnline.Solicitante userLogin) {
            return base.Channel.AgregarSolicitudAsync(solicitud, userLogin);
        }
        
        public void CambiarEstado(Administracion.WSTramitesOnline.Solicitud solicitud, Administracion.WSTramitesOnline.Empleado userLogin) {
            base.Channel.CambiarEstado(solicitud, userLogin);
        }
        
        public System.Threading.Tasks.Task CambiarEstadoAsync(Administracion.WSTramitesOnline.Solicitud solicitud, Administracion.WSTramitesOnline.Empleado userLogin) {
            return base.Channel.CambiarEstadoAsync(solicitud, userLogin);
        }
        
        public Administracion.WSTramitesOnline.Solicitud[] ListadoSolicitudes(Administracion.WSTramitesOnline.Empleado userLogin) {
            return base.Channel.ListadoSolicitudes(userLogin);
        }
        
        public System.Threading.Tasks.Task<Administracion.WSTramitesOnline.Solicitud[]> ListadoSolicitudesAsync(Administracion.WSTramitesOnline.Empleado userLogin) {
            return base.Channel.ListadoSolicitudesAsync(userLogin);
        }
        
        public void AgregarTramite(Administracion.WSTramitesOnline.TipoTramite tramite, Administracion.WSTramitesOnline.Empleado userLogin) {
            base.Channel.AgregarTramite(tramite, userLogin);
        }
        
        public System.Threading.Tasks.Task AgregarTramiteAsync(Administracion.WSTramitesOnline.TipoTramite tramite, Administracion.WSTramitesOnline.Empleado userLogin) {
            return base.Channel.AgregarTramiteAsync(tramite, userLogin);
        }
        
        public void ModificarTramite(Administracion.WSTramitesOnline.TipoTramite tramite, Administracion.WSTramitesOnline.Empleado user) {
            base.Channel.ModificarTramite(tramite, user);
        }
        
        public System.Threading.Tasks.Task ModificarTramiteAsync(Administracion.WSTramitesOnline.TipoTramite tramite, Administracion.WSTramitesOnline.Empleado user) {
            return base.Channel.ModificarTramiteAsync(tramite, user);
        }
        
        public void EliminarTramite(Administracion.WSTramitesOnline.TipoTramite tramite, Administracion.WSTramitesOnline.Empleado user) {
            base.Channel.EliminarTramite(tramite, user);
        }
        
        public System.Threading.Tasks.Task EliminarTramiteAsync(Administracion.WSTramitesOnline.TipoTramite tramite, Administracion.WSTramitesOnline.Empleado user) {
            return base.Channel.EliminarTramiteAsync(tramite, user);
        }
        
        public Administracion.WSTramitesOnline.TipoTramite[] ObtenerTramites() {
            return base.Channel.ObtenerTramites();
        }
        
        public System.Threading.Tasks.Task<Administracion.WSTramitesOnline.TipoTramite[]> ObtenerTramitesAsync() {
            return base.Channel.ObtenerTramitesAsync();
        }
        
        public string ObtenerTipoTramites() {
            return base.Channel.ObtenerTipoTramites();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerTipoTramitesAsync() {
            return base.Channel.ObtenerTipoTramitesAsync();
        }
        
        public Administracion.WSTramitesOnline.TipoTramite BuscarTramite(string idTramite, Administracion.WSTramitesOnline.Empleado user) {
            return base.Channel.BuscarTramite(idTramite, user);
        }
        
        public System.Threading.Tasks.Task<Administracion.WSTramitesOnline.TipoTramite> BuscarTramiteAsync(string idTramite, Administracion.WSTramitesOnline.Empleado user) {
            return base.Channel.BuscarTramiteAsync(idTramite, user);
        }
    }
}
